### ISSUE TITLE
injecting html over ajax

### ISSUE THREAD

**Issue by glenfordwilliams** [Juicy/juicy-html#11]
hi ive been trying to inject some html code received with ajax but i keep getting a null value
code is here, cant seem to get it right with github markdown
https://bpaste.net/show/b7b8a1aeca9b

**Comment by warpech** [comment]
Try `<template is="juicy-html" content$=[[item.excerpt]]></template>`

`juicy-html` is a vanilla custom element, that listens to the mutations of the `content` attribute. 

To use it with Polymer, you need to set the attribute value using Polymer's `$=` notation (read more here: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#attribute-binding

**Comment by glenfordwilliams** [comment]
thanks that solved my problem
