### ISSUE TITLE
Update examples to work in shimmed browsers

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-html#14]
Right now lots of `juicy-html` examples use `document.currentScript` which is supported in Chrome only.

Have to be replaced with `(document._currentScript || document.currentScript)`.

**Comment by tomalec** [comment]
:+1: good catch

**Comment by miyconst** [comment]
I have formatted and fixed `juicy-html/examples`, but those two still don't work under IE;

http://juicy.github.io/juicy-html/examples/inline_markup_w_model_binding.html
http://juicy.github.io/juicy-html/examples/polymer_template_inline.html

Because both `currentScript` and `_currentScript` are not set in IE.

@tomalec can you take a look?

And I have to test in Edge & Safari. Works in Chrome & FF.

**Comment by tomalec** [comment]
hm.. but those should be set by webcomponents.js https://github.com/webcomponents/webcomponentsjs/blob/07f2169ad902be51054fe6f7d63f3b5a6a2618e9/src/HTMLImports/base.js#L58

**Comment by miyconst** [comment]
Yeah.. and it works in FF, but not in IE.

Edge will be tested tonight, don't have latest version at office.

**Comment by miyconst** [comment]
Edge tested - works.

**Comment by miyconst** [comment]
There is nothing can be done in `juicy-html` to fix the examples. This issue should be fixed: This issue requires https://github.com/Juicy/imported-template/issues/21.

Closing this one.
