### ISSUE TITLE
Release a version

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-html#16]
Is there any reason why the version 1.0.2 was not released? There are Safari-related changes on the master branch, which were not yet pulled to Starcounter. Is it secure to release a new version of juicy-html with these changes?

cc @miyconst

**Comment by miyconst** [comment]
No, there is no reason, and yes, it is safe to include the latest version into Starcounter.

Assign the issue on me, if you want me to do that.

**Comment by warpech** [comment]
Since you are the author of the changes, please do so. Thanks!

**Comment by miyconst** [comment]
Released,` /sys/` folder updated.
