### ISSUE TITLE
"bower i juicy-html -S" does not install "example" or "test" folders

### ISSUE THREAD

**Issue by oneezy** [Juicy/juicy-html#19]
"bower i juicy-html -S" does not install "example" or "test" folders

**Comment by tomalec** [comment]
Yes, I have added them explicitly to [`bower.json` ignore](https://github.com/Juicy/juicy-html/blob/master/bower.json#L19)

I did so not to bloat the dependencies folder, as those files are not needed for `juicy-html` to work.

For development you should do as usual `git clone https://github.com/Juicy/juicy-html.git`

Do you find any reason to include them in production package?

**Comment by tomalec** [comment]
I'm closing it as answered. Please, feel free to reopen it, if you have any further comments.
