### ISSUE TITLE
Handle Erors.

### ISSUE THREAD

**Issue by MONKATRON** [Juicy/juicy-html#21]
# A listener/dom if that handles errors in paths. Possibly a duplicate of https://github.com/Juicy/juicy-html/issues/10 #17  but prety F8c^ing urgent. 👍

**Comment by MONKATRON** [comment]
Otherwise a great bit of kit! :)

**Comment by tomalec** [comment]
Thanks for feedback @MONKATRON !.. and sorry for late response..

What kind of errors would you like to catch? URL validation, or just 4xx/5xx?

**Comment by warpech** [comment]
Archiving as not answered by OP. Please reopen if needed
