### ISSUE TITLE
Performance improvement: Bind the model only to Element nodes

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-html#23]
Right now, `juicy-html` binds the model to all nodes in the template, including the Text nodes. This is a performance bottleneck and should be changed to skip all nodes which are not Elements.

Source: https://github.com/Juicy/juicy-html/blob/2d5a5a12d0a2654df69314534b3e12b71f95902c/juicy-html.html#L131

**Comment by warpech** [comment]
Or whoever is calling `attachModel` (it is called from `juicy-html` and `imported-template`) should make sure that in the parameter array there are only elements.

**Comment by tomalec** [comment]
BTW, Does it really affect the performance?
As theoretically such model could still be used, for example for regular text bindings (w/o Polymer)

**Comment by warpech** [comment]
You got me, I didn't really measure how does it affect performance. It just bothered me when debugging something else. I agree that this might be a non-issue. Worth measuring before any work on this.

**Comment by tomalec** [comment]
I will close this issue, as we do not plan to take any specific action until we will notice a significant difference.

Feel free to re-open if you need it.
