### ISSUE TITLE
Make it CEv1 

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-html#27]
Currently the element is written in Custom Elements v0 syntax.
We will need to migrate it eventually.

So far for those who are running V1 environment we suggest Polyfill that makes it possible to run V0 in V1 and vice-versa https://github.com/WebReflection/document-register-element

**Comment by tomalec** [comment]
As suggested at https://github.com/WebReflection/document-register-element/issues/106#issuecomment-327045696, we should [implement `content` (`href`) property setter first - #18](https://github.com/Juicy/juicy-html/issues/18).

Then we could set `content` synchronously via the property. Just `setAttribute` will become async.

@alshakero  WDYT about this one and #18?

**Comment by alshakero** [comment]
I like the `setter` idea. Sounds cleaner and is faster.

Regarding the name in #18. I agree with this https://github.com/Juicy/juicy-html/issues/18#issuecomment-320338863.

**Comment by alshakero** [comment]
This is done, I'll test upwards (in imported-template and sc-include) then PR.

**Comment by tomalec** [comment]
By "This is done" do you mean https://github.com/Juicy/juicy-html/tree/issues/27-CEv1 ?

**Comment by alshakero** [comment]
I wasn't aware of this branch, and I did pretty much the same job  😢

**Comment by tomalec** [comment]
It was done and working in August, tests and demos were passing in Chrome, Firefox, and Edge. The only part that I was missing was integration with Polymer without `dom-bind-notifier` or equivalent at http://127.0.0.1:8081/components/juicy-html/examples/polymer_template_inline.html

**Comment by warpech** [comment]
@tomalec will make this an autonomous CEv1 with `display: none` in shadow root. The work is already started in https://github.com/Juicy/juicy-html/tree/issues/27-CEv1.

We need a release candidate (can be without tests) ASAP.

**Comment by tomalec** [comment]
PR is waiting for review https://github.com/Juicy/juicy-html/pull/35
I added `display:none` not to introduce SD dependency, make it cheaper and simpler.
It's not exactly the same behavior, but I hope nobody would like to change display property via CSS.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Juicy/juicy-html/releases/tag/3.0.0
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.0.0
