### ISSUE TITLE
Fix tests for CEv1

### ISSUE THREAD

**Issue by alshakero** [Juicy/juicy-html#28]

**Comment by tomalec** [comment]
The plan is to get the synchronous behavior back. We will use property setter for that, then we could live with the fact that polyfilled CEReactions are async.

**Comment by tomalec** [comment]
Starting from https://github.com/Juicy/juicy-html/releases/tag/2.0.0 we have property setters which are synchronous even when polyfilled by `document-register-element`, so I'd say it's no longer a problem.
