### ISSUE TITLE
Idea: Handle pre-upgrade state

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-html#30]
### Steps to reproduce

1. create `juicy-html` before loading its definition.
   ```js
    const juicyHtml = document.createElement('template', 'juicy-html');
    ```
2. attach a property to it
    ```js
    juicyHtml.model = {}; juicyHtml.href = "file.html"; juicyHtml.html = "foo";
    ```
3. load definition
    ```html
    <link rel="import" href="juicy-html.html">
    ```

### Expected result
Properites are still as they were.
### Actual result
Ther are cleared with defaults

### Browsers affected
n/a

### Notes

This is mostly problematic due to attribute reflection, as we cannot reflect props to attrs before upgrade, after upgrade it may be confusing what is important attribute (`null`) or property (`foo`);

@warpech @alshakero WDYT?

**Comment by warpech** [comment]
Is this nice to have or a requirement for Polymer 2.0?

**Comment by miyconst** [comment]
This issue has become serious with the latest [HTML imports](https://webcomponents.github.io/polyfills/html-imports/) removal from the browsers. With Polyfill it often happens that Polymer applies bound values prior to the element upgrade, thus either `href` or `model` values are set, but ignored.

Sample code to test:

```html
<dom-bind id="palindrom-root">
    <template>
        <imported-template href="[[model.ViewModel.Html]]" model="[[model.ViewModel]]"></imported-template>
    </template>
</dom-bind>
```
