### ISSUE TITLE
⏰ Tests are failing on Travis

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-html#44]
Tests are failing on Travis. I know @tomalec already spent a lot of time trying to fix this. @alshakero maybe you have an idea why's that?

@tomalec wrote on Slack:

> You can check my progress in isolation at https://github.com/Juicy/juicy-html/tree/travis-bug but it's still messy as hell.

**Comment by alshakero** [comment]
I'll investigate

**Comment by warpech** [comment]
@alshakero any chance to look into this soon?

**Comment by alshakero** [comment]
I'm looking at it! @tomalec and I agreed this morning.

**Comment by alshakero** [comment]
PR https://github.com/Juicy/juicy-html/pull/46

**Comment by warpech** [comment]
Closing as done
